api/urls.py
from django.urls import path, include
from api import views

app_name = 'api'
urlpatterns = [
    path("first_page/", views.first_page, name='first_page'),
    path("wen/", views.wen, name='wen'),
    path("register/", views.register, name='register'),
    path("modify/", views.modify),
]

article/urls.py
from django.urls import path, include
from article import views
app_name = 'article'
urlpatterns = [
    path("upload_img/", views.upload_img,name='upload_img'),
    path("get_all_img/", views.get_all_img,name='get_all_img'),
    path("add_article/", views.add_article,name='add_article'),
    path("get_all_article/", views.get_all_article,name='get_all_article'),
    path("edit_article/", views.edit_article,name='edit_article'),
]

home/urls.py
from django.urls import path, include
from home import views
urlpatterns = [
    path('index/', views.main, name='home_index'),
    path('login/', views.login, name='login'),
    path('get_code/', views.get_code, name='get_code'),
    path('check_user/', views.check_user, name='check_user'),
]

rbac/urls.py
from django.urls import path, include
from rbac import views
app_name = 'rbac'
urlpatterns = [
    path("login/", views.login,name='login'),
    path("check_user/", views.check_user,name='check_user'),

]

user/urls.py
from django.urls import path
from user import views
app_name = 'user'
urlpatterns = [
    path("get_all_user/", views.get_all_user,name='get_all_user'),
    path("add_user/", views.add_user,name='edit_user'),
    path("edit_user/", views.edit_user,name='edit_user'),
    path("get_added_num/", views.get_added_num,name='get_added_num'),
    path("get_map_data/", views.get_map_data,name='get_map_data'),
]

home/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from mutagen.mp3 import MP3


class TAdmin(models.Model):
    username = models.CharField(max_length=50, blank=True, null=True)
    password = models.CharField(max_length=50, blank=True, null=True)
    salt = models.CharField(max_length=20, blank=True, null=True)
    status = models.IntegerField(blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 't_admin'


class TAlbum(models.Model):
    album_title = models.CharField(max_length=50, blank=True, null=True)
    thumbnail_url = models.ImageField(upload_to='album_img')
    author = models.CharField(max_length=50, blank=True, null=True)
    bordcaster = models.CharField(max_length=50, blank=True, null=True)
    chapter_num = models.IntegerField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    publish_time = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    status = models.IntegerField(blank=True, null=True)
    rating = models.DecimalField(max_digits=8, decimal_places=1, blank=True, null=True)

    class Meta:
        db_table = 't_album'


class TAudioChapter(models.Model):
    chapter_name = models.CharField(max_length=50, blank=True, null=True)
    audio_size = models.CharField(max_length=50, blank=True, null=True)
    audio_duration = models.CharField(max_length=50, blank=True, null=True)
    audio_url = models.FileField(upload_to='audio')
    audio_id =  models.CharField(max_length=100, blank=True, null=True)
    publish_time = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    class Meta:
        db_table = 't_audio_chapter'


class TArticle(models.Model):
    id = models.IntegerField(primary_key=True)
    thumbnail_url = models.CharField(max_length=100, blank=True, null=True)
    title = models.CharField(max_length=50, blank=True, null=True)
    status = models.IntegerField(blank=True, null=True)
    publish_date = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    teacher = models.ForeignKey('TTeacher', models.DO_NOTHING, blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    pic_urls = models.CharField(max_length=100, blank=True, null=True)
    article_category = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 't_article'


class ArticleImg(models.Model):
    img_url = models.ImageField(upload_to='article_img')

    class Meta:
        managed = False
        db_table = "t_article_img"


class TSlidpic(models.Model):
    url = models.ImageField(upload_to='slidpic')
    title = models.CharField(max_length=50, blank=True, null=True)
    status = models.IntegerField(blank=True, null=True)
    upload_time = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    class Meta:
        managed = False
        db_table = 't_slidpic'


class TTask(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)
    user = models.ForeignKey('TUser', models.DO_NOTHING, blank=True, null=True)
    status = models.IntegerField(blank=True, null=True)
    task_category = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 't_task'


class TTaskCounter(models.Model):
    count = models.IntegerField(blank=True, null=True)
    name = models.CharField(max_length=20, blank=True, null=True)
    crate_date = models.DateTimeField(blank=True, null=True)
    task = models.ForeignKey(TTask, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 't_task_counter'


class TTeacher(models.Model):
    thumbnail = models.CharField(max_length=50, blank=True, null=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    status = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 't_teacher'


class TUser(models.Model):
    user_id = models.IntegerField(primary_key=True)
    username = models.CharField(max_length=50, blank=True, null=True)
    password = models.CharField(max_length=50, blank=True, null=True)
    register_time = models.DateTimeField(auto_now_add=True)
    thumbnail_url = models.ImageField(upload_to='userthumbnail')
    user_info = models.CharField(max_length=100, blank=True, null=True)
    nickname = models.CharField(max_length=50, blank=True, null=True)
    gender = models.IntegerField(blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    address = models.CharField(max_length=30, blank=True, null=True)
    status = models.IntegerField(blank=True, null=True)
    salt = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 't_user'

home/views.py
from redis import Redis
from django.http import JsonResponse
from django.shortcuts import render, HttpResponse
from django.views.decorators.csrf import csrf_exempt

from czh_cmfz.settings import *
from utilities.generate_code import random_code
from utilities.send_msg import YunPian

import re


def main(request):
    return render(request, 'home.html')


def login(request):
    return render(request, 'login.html')

redis = Redis(host="localhost", port=PORT)
@csrf_exempt
def get_code(request):
    """
    发送手机验证码
    :param request: 接受输入的手机号码
    :return: 发送状态
    """
    phone = request.POST.get('mobile')
    # 正则判断输入手机号是否合法
    result = re.match(r"^1[35678]\d{9}$", phone)
    if result:
        saved_code = redis.get(f'{phone}_1')
        if saved_code:
            return JsonResponse({'status': 0, 'msg': '已经发送了验证码请检查！'})
        code = random_code()
        print(f'验证码：{code}')
        yun_pian = YunPian(API_KEY)
        # yun_pian.send_msg(phone,code)

        # 将手机号与对应的验证码存入redis  防止无限制发送

        redis.set(f"{phone}_1", code, 120)
        # 保证验证码的有效期
        redis.set(f"{phone}_2", code, 600)

        return JsonResponse({'status': 1, 'msg': '发送成功！请查收！'})
    else:
        return JsonResponse({'status': 0, 'msg': '请输入合法的手机号！'})


def check_user(request):
    """
    用户登陆信息校验
    :param request:用户手机号验证码
    :return:成功跳转，失败提示信息
    """
    phone = request.GET.get('mobile')
    code = request.GET.get('code')
    phone_result = re.match(r"^1[35678]\d{9}$", phone)
    code_result = re.match(r"\d{4}$", code)
    if phone_result and code_result:
        try:
            saved_code = redis.get(f'{phone}_2')
            if saved_code.decode() == code:
                return JsonResponse({'status': 1, 'msg': '登陆成功！'})
        except BaseException as error:
            print(error)
            return JsonResponse({'status': 0, 'msg': f'{error}请先发送验证码！'})
        return JsonResponse({'status': 0, 'msg': '登陆失败！'})
    else:
        return JsonResponse({'status': 0, 'msg': '有字段输入不合法！请检查！'})

templates/added_user_echart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>近七天新增用户趋势</title>
    <script src="{% static 'boot/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'echart/echarts.min.js' %}"></script>

</head>
<body>

<div id="main" style="width: 800px;height:500px;"></div>
<script type="text/javascript">
    // 基于准备好的dom，初始化echarts实例
    var myChart = echarts.init(document.getElementById('main'));

    // 指定图表的配置项和数据
    var option = {
        title: {
            text: '近七天新增用户数'
        },
        tooltip: {},
        legend: {
            data: ['人数']
        },
        xAxis: {
            data: []
        },
        yAxis: {},

    };

    // 使用刚指定的配置项和数据显示图表。
    myChart.setOption(option);

    // 发送Ajax请求获取数据
    $.ajax({
        url: '{% url 'user:get_added_num' %}',
        datatype: 'json',
        type: 'get',
        success: function (data) {
            myChart.setOption({
                xAxis: {
                    data: data.x
                },
                series: [{
                    name: '人数',
                    data: data.y,
                    type: 'line',
                    color: 'lightblue',
                    areaStyle: {},
                    smooth: true
                }]
            })
        }
    })
</script>
</body>
</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>持名法州系统首页</title>
    <link rel="stylesheet" href="{% static 'boot/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'boot/css/back.css' %}">
    <link rel="stylesheet" href="{% static 'jqgrid/css/trirand/ui.jqgrid-bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'jqgrid/css/jquery-ui.css' %}">
    <script src="{% static 'boot/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'boot/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'jqgrid/js/trirand/src/jquery.jqGrid.js' %}"></script>
    <script src="{% static 'jqgrid/js/trirand/i18n/grid.locale-cn.js' %}"></script>
    <script src="{% static 'echart/echarts.min.js' %}"></script>
    <script src="{% static 'echart/china.js' %}"></script>
    <script src="{% static 'kindeditor/kindeditor-all-min.js' %}"></script>
    <script src="{% static 'kindeditor/lang/zh-CN.js' %}"></script>
    <script>
        KindEditor.ready(function (K) {
            K.create('#editor_id',
                {
                    width: '800px',
                    height: '300px',
                    items: [
                        'source', '|', 'undo', 'redo', '|', 'preview', 'print', 'template', 'code', 'cut', 'copy', 'paste',
                        'plainpaste', 'wordpaste', '|', 'justifyleft', 'justifycenter', 'justifyright',
                        'justifyfull', 'insertorderedlist', 'insertunorderedlist', 'indent', 'outdent', 'subscript',
                        'superscript', 'clearhtml', 'quickformat', 'selectall', '|', 'fullscreen', '/',
                        'formatblock', 'fontname', 'fontsize', '|', 'forecolor', 'hilitecolor', 'bold',
                        'italic', 'underline', 'strikethrough', 'lineheight', 'removeformat', '|', 'image', 'multiimage',
                        'flash', 'media', 'insertfile', 'table', 'hr', 'emoticons', 'baidumap', 'pagebreak',
                        'anchor', 'link', 'unlink', '|', 'about'
                    ],
                    resizeType: 2,
                    uploadJson: "{% url 'article:upload_img' %}",
                    allowFileManager: true,
                    fileManagerJson: "",
                    afterBlur: function () {
                    }
                }
            );
        });
    </script>
</head>
<body>

<!-- 导航 -->
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- 导航标题 -->
        <div class="navbar-header">
            <a href="{% url 'home_index' %}" class="navbar-brand">持名法州管理系统</a>
        </div>
        <!-- 导航内容 -->
        <ul class="nav navbar-nav navbar-right">
            <li><a>欢迎:</a></li>
            <li><a href="#">退出登录 <span class="glyphicon glyphicon-log-out"></span></a></li>
        </ul>
    </div>
</nav>

<!-- 分割网页12份 -->
<div class="container-fluid">

    <!-- 左侧手风琴 -->
    <div class="col-xs-2">
        <!-- 用户管理 -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title">
                    <a href="#aa" data-toggle="collapse" data-parent="#accordion"><h4>用户管理</h4></a>
                </div>
            </div>
            <div id="aa" class="panel-collapse collapse ">
                <div class="panel-body">
                    <ul class="nav nav-pills nav-stacked">
                        {% for menu in request.session.menu_list %}
                            {% if menu.sup_menu_id == 1 %}
                                <li>
                                    <a style="font-weight: bold;"
                                       href="javascript:$('#centerLayout').load('/static/static_html'+'{{ menu.url }}')">{{ menu.title }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>

        <!-- 文章管理 -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title">
                    <a href="#bb" data-toggle="collapse" data-parent="#accordion"><h4>文章管理</h4></a>
                </div>
            </div>
            <div id="bb" class="panel-collapse collapse ">
                <div class="panel-body">
                    <ul class="nav nav-pills nav-stacked">
                        {% for menu in request.session.menu_list %}
                            {% if menu.sup_menu_id == 2 %}
                                <li>
                                    <a style="font-weight: bold;"
                                       href="javascript:$('#centerLayout').load('/static/static_html'+'{{ menu.url }}')">{{ menu.title }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>

        </div>

        <!-- 专辑管理 -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title">
                    <a href="#cc" data-toggle="collapse" data-parent="#accordion"><h4>专辑管理</h4></a>
                </div>
            </div>
            <div id="cc" class="panel-collapse collapse ">
                <div class="panel-body">
                    <ul class="nav nav-pills nav-stacked">
                        {% for menu in request.session.menu_list %}
                            {% if menu.sup_menu_id == 3 %}
                                <li>
                                    <a style="font-weight: bold;"
                                       href="javascript:$('#centerLayout').load('/static/static_html'+'{{ menu.url }}')">{{ menu.title }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>

        <!-- 轮播图管理 -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title">
                    <a href="#dd" data-toggle="collapse" data-parent="#accordion"><h4>轮播图管理</h4></a>
                </div>
            </div>
            <div id="dd" class="panel-collapse collapse ">
                <div class="panel-body">
                    <ul class="nav nav-pills nav-stacked">
                        {% for menu in request.session.menu_list %}
                            {% if menu.sup_menu_id == 4 %}
                                <li>
                                    <a style="font-weight: bold;"
                                       href="javascript:$('#centerLayout').load('/static/static_html'+'{{ menu.url }}')">{{ menu.title }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>

    </div>

    <!-- 右侧欢迎、轮播图 -->
    <div class="col-xs-10" id="centerLayout">

        <!-- 欢迎界面 -->
        <div class="jumbotron">
            <h2 style="color:#898080;">欢迎来到持名法州后台管理系统</h2>
        </div>

        <!-- 轮播图 -->
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="{% static 'img/shouye/ad02.png' %}" style="width: 1000px">
                    <div class="carousel-caption"></div>
                </div>
                <div class="item">
                    <img src="{% static 'img/shouye/ad03.png' %}" style="width: 1000px">
                    <div class="carousel-caption"></div>
                </div>
            </div>
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>

<br>
<div class="panel-footer">
    <div class="panel-title">
        <h6 style="text-align: center">@百知教育 baizhi@zparkhr.com.cn</h6>
    </div>
</div>
</body>
</html>

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>商品后台管理系统</title>
    <link rel="stylesheet" href="{% static 'boot/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'jqgrid/css/trirand/ui.jqgrid-bootstrap.css' %}">
    <script src="{% static 'boot/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'boot/js/bootstrap.min.js' %}"></script>

    <!--发送按钮倒计时代码-->
    <script type="text/javascript">


        var countdown = 60;

        function settime(obj) {
            if (countdown == 0) {
                obj.removeAttribute("disabled");
                obj.value = "免费获取验证码";
                countdown = 60;
                return;
            } else {
                obj.setAttribute("disabled", true);
                obj.value = "重新发送(" + countdown + ")";
                countdown--;
            }
            setTimeout(function () {
                    settime(obj)
                }
                , 1000)
        }

        $(function () {
            $("#forcode").click(function () {
                let phone = check_phone();
                if (phone) {
                    // 根据用户输入的手机号发送验证码
                    $.ajax({
                        type: 'post',
                        data: {mobile: phone},
                        url: "{% url 'get_code' %}",
                        success: function (data) {
                            console.log(data.status);
                            if (data.status === 1) {
                                alert(data.msg)
                            } else {
                                alert(data.msg)
                            }
                        }
                    });
                } else {
                    alert("请输入合法的手机号！")
                }
            });

            // blur时检查手机号是否合法
            $("#mobile").blur(function () {
                check_phone()
            });

            // blur时检查验证码是否合法
            $("#basic-url").blur(function () {
                check_code()
            });

            // 验证表单数据是否合法
            $("#loginButtonId").click(function () {
                let checkPhoneRes = check_phone();
                let checkCodeRes = check_code();
                // 如果两项输入都合法则发送请求
                if(checkPhoneRes && checkCodeRes){
                    $.ajax({
                        url: "{% url 'check_user' %}",
                        datatype: 'json',
                        type: 'get',
                        // 获取id为loginForm的表单数据
                        data: $("#loginForm").serialize(),
                        success: function (data) {
                            // 根据返回值判断是否登录成功  成功则跳转到首页
                            if (data.status === 1){
                                location.href = '{% url 'home_index' %}'
                            } else {
                                alert(data.msg)
                            }
                        }
                    });
                } else {
                    alert('有字段输入不合法！请检查！')
                }
            });
        });

        // 输入手机号正则匹配
        function check_phone() {
            // 获取输入的手机号
            let phone = $("#mobile").val();
            // 手机号提示信息
            let phone_msg = $("#phone_msg");
            // 正则表达式判断
            let phone_re = /^1[3-578]\d{9}$/;
            if (phone_re.test(phone)) {
                phone_msg.html('手机号输入合法');
                phone_msg.css('color', 'green');
                return phone
            } else {
                phone_msg.html('请输入合法手机号！');
                phone_msg.css('color', 'red');
                return false
            }
        }

        // 输入验证码正则匹配
        function check_code() {
            let code = $("#basic-url").val();
            let code_msg = $("#code_msg");
            // 正则表达式判断
            let code_re = /\d{4}$/;
            if (code_re.test(code)) {
                code_msg.html('验证码输入合法');
                code_msg.css('color', 'green');
                return code
            } else {
                code_msg.html('请输入合法验证码！');
                code_msg.css('color', 'red');
                return false
            }
        }

    </script>

</head>


<body>

<!--手机号码输入框代码-->
<div class="container">
    <div class="form-group">
        <div class="col-lg-10">
            <form id="loginForm" role="form" action="" method="post" class="form-horizontal">

                <label for="mobile" class="">手机号码:</label>
                <div class="input-group m-bot15" style="width: 400px">
                    <input type="text" maxlength='11' class="form-control" required id="mobile" name="mobile"
                           placeholder="手机号码">
                    <span class="input-group-btn">
                         <input type="button" id="forcode" onclick="settime(this)" value="免费获取验证码" class="btn btn-success">
                    </span>
                </div>
                <span id="msgDiv"></span>
                <p class="help-block" id="phone_msg">请填写绑定手机号</p>
                <label for="basic-url" class="">验证码：</label>
                <div class="input-group">
                    <input type="text" maxlength="4" class="form-control" id="basic-url" required name="code">
                </div>
                <p class="help-block" id="code_msg">请填写接收的验证码</p>

                <p class="help-block"></p>
                <div class="input-group">
                    <input class="btn btn-success" type="button" id="loginButtonId" value="登录">
                </div>
            </form>
        </div>
    </div>
</div>

</body>
</html>

templates/login_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>持名法州后台管理系统登陆</title>
    <link rel="stylesheet" href="{% static 'boot/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'jqgrid/css/trirand/ui.jqgrid-bootstrap.css' %}">
    <script src="{% static 'boot/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'boot/js/bootstrap.min.js' %}"></script>
</head>
<body>
<br><br><br>
<div class="container">
    <div class="form-group">
        <div class="col-lg-10">
            <form id="loginForm" role="form" action="{% url 'rbac:check_user' %}" method="post" class="form-horizontal">
                {% csrf_token %}
                <label for="mobile" class="">用户名:</label>
                <div class="input-group m-bot15" style="width: 300px">
                    <input type="text" class="form-control" required id="username" name="username">

                </div>
                <br>
                <label for="basic-url" class="">密码：</label>
                <div class="input-group" style="width: 300px">
                    <input type="password" class="form-control" required id="password" name="password">
                </div>
                <br>
                <div class="input-group">
                    <button type="submit" class="btn btn-success" id="loginButtonId" value="登录" onclick="check_username()">登陆</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    function check_username() {
        $.ajax({
            type: "POST",
            url: "{% url "rbac:check_user" %}",
            data: $("#loginForm").serialize(),
            success: function (data) {
                if (data.status === 1) {
                    location.href = '{% url 'home_index' %}'
                } else {
                    alert(data.msg);
                    location.reload()
                }
            }
        });

    }
</script>
</body>
</html>

templates/user_num_map.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>全国注册用户数量分布图</title>
    <script src="{% static 'boot/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'echart/echarts.min.js' %}"></script>
    <script src="{% static 'echart/china.js' %}"></script>

</head>
<body>
<div id="main" style="width: 800px;height:500px;"></div>
<script type="text/javascript">
    // 基于准备好的dom，初始化echarts实例
    var myChart = echarts.init(document.getElementById('main'));

    // 指定图表的配置项和数据
    var option = {
        title: {
            text: '每⽉⽤户注册量',
            subtext: '纯属虚构',
            left: 'center'
        },
        tooltip: {
            trigger: 'item'
        },
        legend: {
            orient: 'vertical',
            left: 'left',
            data: ['1⽉', '2⽉', '3⽉']
        },
        visualMap: {
            min: 0,
            max: 200,
            left: 'left',
            top: 'bottom',
            text: ['⾼', '低'], // ⽂本，默认为数值⽂本
            calculable: true
        },
        toolbox: {
            show: true,
            orient: 'vertical',
            left: 'right',
            top: 'center',
            feature: {
                mark: {show: true},
                dataView: {show: true, readOnly: false},
                restore: {show: true},
                saveAsImage: {show: true}
            }
        },
        series: [
            {
                name: '1⽉',
                type: 'map',
                mapType: 'china',
                roam: false,
                label: {
                    normal: {
                        show: false
                    },
                    emphasis: {
                        show: true
                    }
                },
                data: []
            },
        ]
    };
    // 使用刚指定的配置项和数据显示图表。
    myChart.setOption(option);

    // 发送Ajax请求获取数据
    $.ajax({
        url: '{% url 'user:get_map_data' %}',
        datatype: 'json',
        type: 'get',
        success: function (data) {
            myChart.setOption({
                series: [
                    {
                        name: '1⽉',
                        type: 'map',
                        mapType: 'china',
                        roam: false,
                        label: {
                            normal: {
                                show: false
                            },
                            emphasis: {
                                show: true
                            }
                        },
                        data: data
                    },
                ]
            })
        }
    })

</script>

</body>
</html>